#!/usr/bin/env python3
"""Convert a Hevy workout export into the training log the profile reads.

    python3 tools/import_hevy.py ~/Downloads/workouts.csv

Hevy writes one row per set. Rows sharing a start and end time are one
session, and its duration is end_time - start_time.

Only the date and the duration are kept. The export also carries exercise
names, weights, reps, RPE and free-text notes; none of that belongs in a
public repository, so none of it is written out.
"""

import argparse
import csv
import os
import sys
from datetime import datetime

HEADER = """\
# Training log. One row per session; the profile sparkline reads this file.
# Columns: date (YYYY-MM-DD), minutes (integer)
# Lines starting with # are ignored, so paste a Hevy or Strava export under
# the header and delete any columns you do not want.
#
# Generated by tools/import_hevy.py from a Hevy export: one Hevy row per set,
# collapsed to one row per session, duration = end_time - start_time.
date,minutes
"""

# Hevy's export stamps look like "Sep 2, 2026, 6:59 PM". The zero-padded and
# non-padded forms both appear depending on locale, and %-d is not portable,
# so try the handful of shapes rather than guessing one.
TIME_FORMATS = (
    "%b %d, %Y, %I:%M %p",
    "%d %b %Y, %H:%M",
    "%Y-%m-%d %H:%M:%S",
    "%Y-%m-%dT%H:%M:%S",
)

REQUIRED = ("start_time", "end_time")
MAX_PLAUSIBLE_MINUTES = 6 * 60


def parse_time(raw):
    raw = (raw or "").strip()
    for fmt in TIME_FORMATS:
        try:
            return datetime.strptime(raw, fmt)
        except ValueError:
            continue
    return None


def read_sessions(path):
    """Collapse set rows into (date, minutes), sorted, plus a list of skips."""
    with open(path, newline="", encoding="utf-8-sig") as fh:
        reader = csv.DictReader(fh)
        missing = [c for c in REQUIRED if c not in (reader.fieldnames or [])]
        if missing:
            raise SystemExit(
                "{}: not a Hevy export, missing column(s): {}\nFound: {}".format(
                    path, ", ".join(missing),
                    ", ".join(reader.fieldnames or ["<none>"])))
        spans, skipped = {}, []
        for n, row in enumerate(reader, start=2):
            start = parse_time(row.get("start_time"))
            end = parse_time(row.get("end_time"))
            if not start or not end:
                skipped.append((n, "unreadable timestamp"))
                continue
            spans[(start, end)] = row.get("title", "").strip()

    sessions, dropped = [], []
    for (start, end), title in sorted(spans.items()):
        minutes = round((end - start).total_seconds() / 60)
        label = title or start.strftime("%d %b %Y")
        if minutes <= 0:
            # A timer stopped before it started, or a session logged after the
            # fact with no elapsed time. Counting it as 0 would drag the
            # average down, so it is dropped and reported rather than kept.
            dropped.append((label, "{} min".format(minutes)))
            continue
        if minutes > MAX_PLAUSIBLE_MINUTES:
            # Almost always a timer left running overnight.
            dropped.append((label, "{} min, over {}h".format(
                minutes, MAX_PLAUSIBLE_MINUTES // 60)))
            continue
        sessions.append((start.date(), minutes))
    return sorted(sessions), skipped, dropped


def read_existing(path):
    if not os.path.exists(path):
        return []
    out = []
    with open(path, newline="", encoding="utf-8") as fh:
        body = [ln for ln in fh if not ln.lstrip().startswith("#")]
    for row in csv.DictReader(body):
        try:
            day = datetime.strptime((row.get("date") or "").strip()[:10],
                                    "%Y-%m-%d").date()
            out.append((day, int(float(row.get("minutes") or 0))))
        except (ValueError, TypeError):
            continue
    return sorted(out)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("export", help="workouts.csv exported from Hevy")
    ap.add_argument("--out", default="data/training.csv", help="target log")
    ap.add_argument("--dry-run", action="store_true",
                    help="report what would change and write nothing")
    args = ap.parse_args(argv)

    sessions, skipped, dropped = read_sessions(args.export)
    if not sessions:
        raise SystemExit("no usable sessions found in {}".format(args.export))

    before = read_existing(args.out)
    added = len(set(sessions) - set(before))
    removed = len(set(before) - set(sessions))

    print("{} sessions, {} to {}".format(
        len(sessions), sessions[0][0], sessions[-1][0]))
    print("total {:,} minutes, average {} min".format(
        sum(m for _, m in sessions),
        round(sum(m for _, m in sessions) / len(sessions))))
    for line, why in skipped:
        print("  skipped row {}: {}".format(line, why), file=sys.stderr)
    for label, why in dropped:
        print("  dropped session {}: {}".format(label, why), file=sys.stderr)
    # The export replaces the log rather than merging into it, so say plainly
    # what leaves as well as what arrives.
    print("against {}: +{} new, -{} no longer present".format(
        args.out, added, removed))

    if args.dry_run:
        print("dry run, nothing written")
        return 0

    directory = os.path.dirname(args.out)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(HEADER)
        for day, minutes in sessions:
            fh.write("{},{}\n".format(day.isoformat(), minutes))
    print("wrote {}".format(args.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
